# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StopWatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimerWin(object):
    def setupUi(self, TimerWin):
        TimerWin.setObjectName("TimerWin")
        TimerWin.resize(494, 505)
        TimerWin.setAutoFillBackground(False)
        TimerWin.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.centralwidget = QtWidgets.QWidget(TimerWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Hr_lb = QtWidgets.QLCDNumber(self.centralwidget)
        self.Hr_lb.setObjectName("Hr_lb")
        self.horizontalLayout_2.addWidget(self.Hr_lb)
        self.Min_lb = QtWidgets.QLCDNumber(self.centralwidget)
        self.Min_lb.setObjectName("Min_lb")
        self.horizontalLayout_2.addWidget(self.Min_lb)
        self.Sec_lb = QtWidgets.QLCDNumber(self.centralwidget)
        self.Sec_lb.setObjectName("Sec_lb")
        self.horizontalLayout_2.addWidget(self.Sec_lb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.start_btn.setObjectName("start_btn")
        self.start_btn.setIcon(QtGui.QIcon('Icons\Start.png'))
        self.horizontalLayout.addWidget(self.start_btn)
        self.Restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Restart_btn.setObjectName("Restart_btn")
        self.Restart_btn.setIcon(QtGui.QIcon('Icons\black-panel-restart-system-icon--6.png'))
        self.horizontalLayout.addWidget(self.Restart_btn)
        self.Stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Stop_btn.setObjectName("Stop_btn")
        self.Stop_btn.setIcon(QtGui.QIcon('Icons/Stop.png'))
        self.horizontalLayout.addWidget(self.Stop_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.exitStp = QtWidgets.QPushButton(self.centralwidget)
        self.exitStp.setStyleSheet("background-color: rgb(255, 35, 75);\n"
"")
        self.exitStp.setObjectName("exitStp")
        self.exitStp.setIcon(QtGui.QIcon('Icons\Exit.png'))
        self.verticalLayout.addWidget(self.exitStp)
        TimerWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimerWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 26))
        self.menubar.setObjectName("menubar")
        TimerWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TimerWin)
        self.statusbar.setObjectName("statusbar")
        TimerWin.setStatusBar(self.statusbar)

        self.retranslateUi(TimerWin)
        QtCore.QMetaObject.connectSlotsByName(TimerWin)

    def retranslateUi(self, TimerWin):
        _translate = QtCore.QCoreApplication.translate
        TimerWin.setWindowTitle(_translate("TimerWin", "Stop watch"))
        self.label_2.setText(_translate("TimerWin", "Hr"))
        self.label_3.setText(_translate("TimerWin", "Min"))
        self.label.setText(_translate("TimerWin", "Sec"))
        self.start_btn.setText(_translate("TimerWin", "Start"))
        self.Restart_btn.setText(_translate("TimerWin", "Restart"))
        self.Stop_btn.setText(_translate("TimerWin", "Stop"))
        self.exitStp.setText(_translate("TimerWin", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimerWin = QtWidgets.QMainWindow()
    ui = Ui_TimerWin()
    ui.setupUi(TimerWin)
    TimerWin.show()
    sys.exit(app.exec_())
